/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#bdc7de",
        "on-tertiary-fixed-variant": "#703800",
        "on-secondary": "#273143",
        "on-background": "#e0e2eb",
        "primary-container": "#3192fc",
        "tertiary-fixed": "#ffdcc5",
        "primary-fixed": "#d5e3ff",
        "surface-container-high": "#262a31",
        "tertiary-fixed-dim": "#ffb782",
        "primary": "#a6c8ff",
        "surface-dim": "#10141a",
        "primary-fixed-dim": "#a6c8ff",
        "on-surface": "#e0e2eb",
        "error-container": "#93000a",
        "secondary-fixed": "#d9e3fb",
        "on-secondary-container": "#aeb8d0",
        "surface-tint": "#a6c8ff",
        "on-secondary-fixed-variant": "#3d475a",
        "surface-container-lowest": "#0b0e14",
        "background": "#10141a",
        "on-secondary-fixed": "#111c2d",
        "outline": "#8a919e",
        "on-error-container": "#ffdad6",
        "secondary-container": "#3f495d",
        "tertiary-container": "#de7403",
        "on-tertiary-fixed": "#301400",
        "secondary": "#bdc7de",
        "on-primary": "#00315f",
        "error": "#ffb4ab",
        "on-tertiary-container": "#452000",
        "on-primary-fixed-variant": "#004786",
        "on-primary-fixed": "#001c3b",
        "surface-variant": "#31353c",
        "inverse-on-surface": "#2d3037",
        "surface": "#10141a",
        "surface-container-highest": "#31353c",
        "outline-variant": "#404753",
        "on-surface-variant": "#c0c7d5",
        "inverse-surface": "#e0e2eb",
        "on-error": "#690005",
        "surface-container-low": "#181c22",
        "surface-container": "#1c2026",
        "on-tertiary": "#4f2500",
        "tertiary": "#ffb782",
        "inverse-primary": "#005fb0",
        "on-primary-container": "#002a53",
        "surface-bright": "#363940"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-lg": "32px",
        "stack-md": "16px",
        "unit": "4px",
        "gutter": "24px",
        "stack-sm": "8px",
        "container-padding": "32px"
      },
      fontFamily: {
        "display-lg-mobile": ["Hanken Grotesk"],
        "body-md": ["Inter"],
        "display-lg": ["Hanken Grotesk"],
        "body-lg": ["Inter"],
        "code-sm": ["Geist"],
        "headline-md": ["Hanken Grotesk"],
        "label-mono": ["Geist"]
      },
      fontSize: {
        "display-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "code-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-mono": ["13px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
